# 1. Broadcasting
Numpy'nin broadcasting özelliği, farklı boyutlardaki diziler üzerinde aritmetik işlemler yapmayı kolaylaştırır.

In [1]:
import numpy as np

# İki boyutlu dizi
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Tek boyutlu dizi
b = np.array([1, 0, 1])

# Broadcasting ile toplama
result = a + b
print(result)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


# 2. Gelişmiş Diziler
Numpy'de maskeleme, boolean diziler kullanarak veri seçme ve filtreleme işlemleri yapmayı sağlar.

In [2]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = data % 2 == 0  # Çift sayıları seçme maskesi

# Maskeyi uygulama
even_data = data[mask]
print(even_data)


[ 2  4  6  8 10]


# 3. Fancy Indexing
Fancy indexing ile, bir diziden belirli indekslerdeki elemanları seçebilirsiniz.

In [3]:
a = np.arange(0, 100, 10)
indices = [1, 3, 5, 7]
selected_elements = a[indices]
print(selected_elements)


[10 30 50 70]


# 4. Çok Boyutlu Dizilerde Çalışma
Numpy, çok boyutlu dizilerle çalışmayı kolaylaştırır.

In [4]:
# Üç boyutlu dizi oluşturma
a = np.random.random((3, 3, 3))

# İlk iki boyutun ortalamasını alma
mean_across_axis_2 = a.mean(axis=2)
print(mean_across_axis_2)

[[0.36086341 0.63940219 0.63664129]
 [0.57604993 0.34325262 0.55481224]
 [0.46449721 0.65552496 0.57327549]]


# 5. Lineer Cebir Fonksiyonları
Numpy, lineer cebir işlemleri için geniş bir fonksiyon seti sunar.

In [5]:
# 2x2 matrisler oluşturma
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Matris çarpımı
result = np.dot(a, b)
print(result)

# Matris tersini alma
inverse = np.linalg.inv(a)
print(inverse)


[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Numpy ile Hızlı Fourier Dönüşümü
Numpy, hızlı Fourier dönüşümü (FFT) için fonksiyonlar sağlar.

In [6]:
# Sinüs dalgası oluşturma
x = np.linspace(0, 10, 100)
y = np.sin(x)

# FFT uygulama
fft_y = np.fft.fft(y)
print(fft_y)


[ 1.79193145e+01+0.00000000e+00j  2.90406819e+01+6.28986843e+00j
 -3.18747680e+01-1.40670162e+01j -6.80074220e+00-4.64799794e+00j
 -3.09680330e+00-2.95681595e+00j -1.73383369e+00-2.20544267e+00j
 -1.06505379e+00-1.76882364e+00j -6.83376206e-01-1.47918651e+00j
 -4.43781497e-01-1.27116185e+00j -2.83072950e-01-1.11357181e+00j
 -1.69856152e-01-9.89506783e-01j -8.70133779e-02-8.88939260e-01j
 -2.45337524e-02-8.05518502e-01j  2.37676830e-02-7.35013733e-01j
  6.18851876e-02-6.74490970e-01j  9.24943247e-02-6.21847884e-01j
  1.17443278e-01-5.75536538e-01j  1.38042638e-01-5.34390674e-01j
  1.55243083e-01-4.97514101e-01j  1.69747994e-01-4.64206254e-01j
  1.82086933e-01-4.33911195e-01j  1.92664808e-01-4.06181838e-01j
  2.01795524e-01-3.80654324e-01j  2.09725474e-01-3.57029335e-01j
  2.16650233e-01-3.35058230e-01j  2.22726624e-01-3.14532622e-01j
  2.28081559e-01-2.95276415e-01j  2.32818608e-01-2.77139670e-01j
  2.37022945e-01-2.59993807e-01j  2.40765099e-01-2.43727820e-01j
  2.44103850e-01-2.282452

# 7. Rastgele Sayı Üretimi
Numpy ile rastgele sayılar üretmek oldukça kolaydır.

In [7]:
# 10 elemanlı rastgele dizi
random_numbers = np.random.rand(10)
print(random_numbers)

# Normal dağılıma sahip rastgele sayılar
normal_random_numbers = np.random.randn(10)
print(normal_random_numbers)


[0.26691767 0.61472297 0.94268573 0.50154015 0.27988303 0.48293233
 0.24389968 0.53780755 0.45570703 0.46534795]
[-0.91501001 -0.80720086 -0.04073217 -1.37642133  0.19416644  0.10398026
 -0.3703536   0.6129869   0.97165484 -0.92241694]


# 8. Numpy'nin where Fonksiyonu
where fonksiyonu, koşullu seçim işlemlerini kolaylaştırır.

In [8]:
x = np.array([1, 2, 3, 4, 5])
y = np.where(x > 2, x, -1)  # x > 2 olan elemanları tut, diğerlerini -1 yap
print(y)


[-1 -1  3  4  5]


# 9. Bellek Kullanımını Azaltma
Numpy'nin astype fonksiyonu ile dizilerin veri tiplerini değiştirebilirsiniz, bu da bellek kullanımını azaltabilir.

In [9]:
# Büyük bir float64 dizisi oluşturma
a = np.random.rand(1000000).astype(np.float64)
print(a.nbytes)

# Diziyi float32'ye dönüştürme
a = a.astype(np.float32)
print(a.nbytes)


8000000
4000000


# 10. İleri Seviye Dizinleme ve Dilimleme
Numpy, dizileri karmaşık şekillerde dilimlemeyi ve dizinlemeyi destekler.

In [10]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

# İkinci ve üçüncü satırları, ikinci ve dördüncü sütunlar arasında seçme
sliced_array = a[1:3, 1:4]
print(sliced_array)

[[ 7  8  9]
 [12 13 14]]
